/* eslint-disable @next/next/no-css-tags */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="css/bootstrap.css" />
      <link rel="stylesheet" href="vendors/linericon/style.css" />
      <link rel="stylesheet" href="css/font-awesome.min.css" />
      <link rel="stylesheet" href="vendors/owl-carousel/owl.carousel.min.css" />
      <link rel="stylesheet" href="css/magnific-popup.css" />
      <link rel="stylesheet" href="vendors/nice-select/css/nice-select.css" />
      <link rel="stylesheet" href="css/style.css"></link>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
